src/Entity/Url.php
<?php

namespace App\Entity;

use App\Repository\UrlRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=UrlRepository::class)
 */
class Url
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $link;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $longUrl;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $domain;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="urls")
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity=UrlStatistic::class, mappedBy="url", orphanRemoval=true)
     */
    private $statistics;

    public function __construct()
    {
        $this->statistics = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(string $link): self
    {
        $this->link = $link;

        return $this;
    }

    public function getLongUrl(): ?string
    {
        return $this->longUrl;
    }

    public function setLongUrl(string $longUrl): self
    {
        $this->longUrl = $longUrl;

        return $this;
    }

    public function getDomain(): ?string
    {
        return $this->domain;
    }

    public function setDomain(string $domain): self
    {
        $this->domain = $domain;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUser(): ?user
    {
        return $this->user;
    }

    public function setUser(?user $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, UrlStatistic>
     */
    public function getStatistics(): Collection
    {
        return $this->statistics;
    }

    public function addStatistic(UrlStatistic $statistic): self
    {
        if (!$this->statistics->contains($statistic)) {
            $this->statistics[] = $statistic;
            $statistic->setUrl($this);
        }

        return $this;
    }

    public function removeStatistic(UrlStatistic $statistic): self
    {
        if ($this->statistics->removeElement($statistic)) {
            // set the owning side to null (unless already changed)
            if ($statistic->getUrl() === $this) {
                $statistic->setUrl(null);
            }
        }

        return $this;
    }
    public function getAllClicks(): int
    {
        $clicks = 0;

        foreach ($this->statistics as $statistic) {
            $clicks += $statistic->getClicks();
        }

        return $clicks;
    }
}

src/Controller/UrlController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Repository\UrlRepository;
use App\Repository\UrlStatisticRepository;
use App\Service\UrlService;
use App\Service\UrlStatisticService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @method User getUser()
 */
class UrlController extends AbstractController
{   
    private UrlService $urlService;
    private UrlStatisticService $urlStatisticService;
    public function __construct(UrlService $urlService,UrlStatisticService $urlStatisticService)
    {
        $this->urlService = $urlService;
        $this->urlStatisticService = $urlStatisticService;
    }
    /**
     * @Route("/url", name="app_url")
     */
    public function index(): Response
    {
        return $this->render('url/index.html.twig', [
            'controller_name' => 'UrlController',
        ]);
    }
    /**
     * @Route("/ajax/shorten", name="url_add")
     */
    public function add(Request $request):Response{
        $longUrl = $request->request->get('url');
        if (!$longUrl){
            return $this->json([
                'statusCode'=> 400,
                'statusText'=> 'MISSING_ARG_URL'
            ]);
        }
        $domain = $this->urlService->parseUrl($longUrl);
        if (!$domain){
            return $this->json([
                'statusCode'=> 500,
                'statusText'=> 'MISSING_ARG_URL'
            ]);
        }
        $url = $this->urlService->addUrl($longUrl,$domain);
        return $this->json([
            'link'=>$url->getLink(),
            'longUrl'=>$url->getLongUrl()
        ]);
    }

    /**
     * @Route("/{hash}", name="url_view")
     */
    public function view(string $hash, UrlRepository $urlRepo):Response
    {
       $url=$urlRepo->findOneBy(['hash'=>$hash]);
       if(!$url){
           return $this->redirectToRoute('app_homepage');
       }
       if (!$url->getUser()) {
        return $this->redirect($url->getLongUrl());
       }
       $urlStatic = $this->urlStatisticService->findOneByUrlAndDate($url,new \DateTime);
       $this->urlStatisticService->incrementUrlStatistic($urlStatic);
       return $this->redirect($url->getLongUrl());

    }
      /**
     * @Route("/user/links", name="url_list")
     */
    public function list( UrlRepository $urlRepo):Response
    {
        $user =$this->getUser();
        if (!$user ||!$user->getUrls()->count()===0) {
           return $this->redirectToRoute('app_homepage');
        }
        return $this->render('url/list.html.twig', [
            'urls' => $user->getUrls()
        ]);

    }
     /**
     * @Route("/ajax/delete/{hash}", name="url_delete")
     */
  
    public function delete(string $hash): Response
    {
        return $this->urlService->deleteUrl($hash);
    }
      /**
     * @Route("/statistics/{hash}", name="url_statistics")
     */
  
    
    public function statistics(string $hash, UrlRepository $urlRepo, UrlStatisticRepository $urlStatisticRepo): Response
    {
        $url = $urlRepo->findOneBy(['hash' => $hash]);

        if (!$url) {
            return $this->redirectToRoute('app_homepage');
        }

        $url_statistics = $urlStatisticRepo->findOneByUrl($url);

        $chart = $this->urlStatisticService->createChart($url_statistics['labels'], $url_statistics['datasets']['data']);

        return $this->render('url/statistics.html.twig', [
            'chart' => $chart,
            'domain' => $url->getDomain()
        ]);
    }
}

templates/url/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes liens{% endblock %}

{% block body %}

    <div class="container mt-5">

        <div class="row">
            <section class="col-lg-6 col-md-12 mx-lg-auto" id="linksSection">
                <div class="list-group">
                    {% for url in urls %}
                        <div class="list-group-item list-group-item-action" id="link_{{ url.hash }}" data-hash="{{ url.hash }}">

                            <div class="d-flex w-100 justify-content-between">
                                <h5 class="mb-1">{{ url.domain }}</h5>
                                <small>{{ url.createdAt|date('d/m/Y') }}</small>
                            </div>

                            <p class="float-start mb-1 fw-bold">
                                {{ url.getAllClicks() }}
                                <i class="far fa-chart-bar"></i>
                            </p>

                            <div class="d-flex w-100 justify-content-between">
                                <a class="text-danger fw-bold" id="anchor_{{ url.hash }}" href="{{ url.link }}" target="_blank">{{ url.link }}</a>
                            </div>

                        </div>
                    {% endfor %}
                   
                </div>
                 <div class="card    p-2" id="shortenCard">
        <form id="shortForm" >
            <div class="col">
                <div class="input-group">
                    <input required name="url" id="url"type="text" autocomplete="off" class="form-control form-control-lg" placeholder="shorten your link" >
                <button id="btnShortenUrl" type="submit " class="btn btn-lg bgRebeccaPurple text-white"> shorten </dbutton>
                </div>
            </div>
        </form>
    </div>
            </section>
        </div>

        <div class="row mt-2">
            <div class="col-lg-4 col-md-12 justify-content-between mx-lg-auto">

                <div class="card">
                    <div class="card-body">
                        <div class="d-flex w-100 justify-content-between" id="actions">
                            <button class="btn btn-sm btn-primary" id="btnCopy" disabled>Copier</button>
                            <button class="btn btn-sm btn-success" id="btnStats" disabled>Statistiques</button>
                            <button class="btn btn-sm btn-danger" id="btnDelete" disabled>Supprimer</button>

                        </div>
                    </div>
                </div>

            </div>
        </div>

        <div class="position-fixed bottom-0 end-0 p-3">
            <div class="toast" id="copyToast" role="alert" aria-live="assertive" aria-atomic="true">
                <div class="toast-header">
                    <strong class="me-auto">Raccourcisseur d'URL</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
                <div class="toast-body">
                    Le lien a bien été copié !
                </div>
            </div>
        </div>


    </div>

{% endblock %}

{% block javascripts %}
    {{ encore_entry_script_tags('list') }}
     {{ encore_entry_script_tags('gsl') }}
{% endblock %}

templates/url/statistics.html.twig
{% extends 'base.html.twig' %}

{% block title %}Stats- {{ domain }}{% endblock %}

{% block body %}
    <div class="container mt-5">

        <div class="text-center">
            <h1>Stats-{{ domain }}</h1>
        </div>

        {{ render_chart(chart) }}
    </div>
{% endblock %}